[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[deploy.variables]]
key = "PORT"
value = "8080"
